[workspace]
authors = [
    "Andreas Albert <andreas.albert@quantco.com>",
    "Oliver Borchert <oliver.borchert@quantco.com>",
]
channels = ["conda-forge"]
name = "tutorial-pycon26-polars-dataframely"
platforms = ["osx-arm64", "linux-64", "linux-aarch64", "win-64"]
version = "0.1.0"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e . && dot -c"
hello-world = "python -c 'import dataframely as dy; import polars as pl; print(\"Hello, World!\"); print(f\"polars version: {pl.__version__}\"); print(f\"dataframely version: {dy.__version__}\"); '"
test = "pytest"

[dependencies]
python = ">=3.14,<3.15"
dataframely = ">=2.9,<3"
polars = ">=1.39.3,<2"
jupyter = "*"
matplotlib = "*"
pip = "*"
hatchling = "*"
pytest = ">=9.0.3,<10"
ruff = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
# graphviz = "*"
# pydot = "*"
